---
- name: Install MariaDB
  hosts: dbservers
  become: yes

  tasks:
    - name: Install MariaDB Server
      yum:
        name: mariadb-server
        state: present

    - name: Start and enable MariaDB
      service:
        name: mariadb
        state: started
        enabled: yes

    - name: Include MariaDB login credentials
      include_vars:
        file: /opt/ansible-vault/devops-ansible/ansible-vault/ansible-mysql/vault/secrets.yml

    - name: Create a MariaDB user
      mysql_user:
        name: "{{ db_user }}"
        password: "{{ db_password }}"
        priv: '*.*:ALL'
        state: present
        host: localhost

    - name: Create a MariaDB database
      mysql_db:
        name: my_database
        state: present
        collation: utf8_general_ci
        encoding: utf8
        login_user: "{{ db_user }}"
        login_password: "{{ db_password }}"