---
- name: Install MariaDB
  hosts: dbservers
  become: yes

  tasks:
    - name: Install Database
      yum:
        name: mariadb-server
        state: present
    
    - name: Start & Enable DB
      service:
        name: mariadb
        state: started

    - name: Include the mariadb login credentials
      include_vars:
        file: /home/ec2-user/ansible-vault/vault/secrets.yml

    - name: Install pip
      yum:
        name: python2-pip
        state: present

    - name: Install PyMySQL
      pip:
        name: pymysql
        state: present

    - name: Create a MariaDB user
      mysql_user:
        name: "{{ db_user }}"
        password: "{{ db_password }}"
        priv: '*.*:ALL'
        state: present
        host: localhost