---
- name: Deploy Web Servers
  hosts: webservers
  tasks:
    - name: Install Apache
      become: yes
      dnf:
        name: httpd
        state: present

    - name: Start Apache and enable on boot
      become: yes
      service:
        name: httpd
        state: started
        enabled: yes

    - name: Create a custom HTML file
      become: yes
      copy:
        content: |
          <!DOCTYPE html>
          <html>
          <head>
            <title>My Custom Web Page</title>
          </head>
          <body>
            <h1>Hello, Ansible!</h1>
            <p>This is a custom HTML page served by Apache.</p>
          </body>
          </html>
        dest: /var/www/html/index.html
