---
- name: Deploy Web Servers
  hosts: webservers
  tasks:
    - name: Install Apache
      become: yes
      dnf:
        name: httpd
        state: present

    - name: Start Apache and enable on boot
      become: yes
      service:
        name: httpd
        state: started
        enabled: yes