---
- name: Install Apache
  become: yes
  dnf:
    name: httpd
    state: present

- name: Start Apache and enable on boot
  become: yes
  service:
    name: httpd
    state: started
    enabled: yes

- name: Copy custom HTML file
  become: yes
  copy:
    src: files/custom.html
    dest: /var/www/html/index.html
